# Generated by Django 4.0.4 on 2022-05-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.IntegerField()),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('outflow', 'Outflow'), ('inflow', 'Inflow')], default='outflow', max_length=10)),
                ('category', models.CharField(max_length=15)),
                ('user_email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
